# Generated by Django 5.0.4 on 2024-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0004_products_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(
                through='cart.CartItem',
                to='products.products'),
        ),
    ]
