# Generated by Django 5.0.6 on 2024-05-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_products'),
        ('products', '0005_alter_products_discount_price_alter_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
